services:
  - type: web
    name: private-chat-room
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: chat-storage
      mountPath: /opt/render/project/src
      sizeGB: 1
